# Generated by Django 3.2.4 on 2024-10-31 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logestadoprueba',
            name='usuarioRegistro',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='usuarioRegistro',
        ),
        migrations.AddField(
            model_name='logestadoprueba',
            name='idUsuarioRegistro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logprueba_registro', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prueba',
            name='idUsuarioRegistro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prueba_registro', to='user.user'),
            preserve_default=False,
        ),
    ]
