# Generated by Django 3.2.4 on 2024-10-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_auto_20241031_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='idEscenario',
        ),
        migrations.AddField(
            model_name='prueba',
            name='escenarioPrueba',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Escenario',
        ),
    ]
