# Generated by Django 3.2.4 on 2024-11-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_auto_20241031_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='idCasoPrueba',
        ),
        migrations.DeleteModel(
            name='CasoPrueba',
        ),
    ]
