services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root558Yuuhd
      MYSQL_DATABASE: db_controlProyecto
      MYSQL_USER: usr_app
      MYSQL_PASSWORD: pass_storng-usr558
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf  # Archivo de configuración del servidor Nginx
      - ./certbot/www:/var/www/certbot  # Carpeta para los desafíos de Certbot
      - ./certbot/conf:/etc/letsencrypt  # Certificados SSL generados por Certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot  # Carpeta para los desafíos de Certbot
      - ./certbot/conf:/etc/letsencrypt  # Certificados SSL generados por Certbot

volumes:
  mysql_data:
