# Generated by Django 3.2.4 on 2024-10-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complejidad',
            fields=[
                ('idComplejidad', models.AutoField(primary_key=True, serialize=False)),
                ('complejidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('idEstadoProyecto', models.AutoField(primary_key=True, serialize=False)),
                ('estadoProyecto', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('idPrioridad', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idProyecto', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRequerimiento', models.DateField()),
                ('usuarioEncargado', models.CharField(max_length=20)),
                ('nombreProyecto', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('fechaEstimadoInicio', models.DateField()),
                ('planificado', models.BooleanField()),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('usuarioRegistro', models.CharField(max_length=20)),
                ('idComplejidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.complejidad')),
                ('idEstadoProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.estadoproyecto')),
                ('idPrioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.prioridad')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRequerimiento',
            fields=[
                ('idTipoRequerimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipoRequerimiento', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('idRecurso', models.AutoField(primary_key=True, serialize=False)),
                ('recurso', models.CharField(max_length=45)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='idTipoRequerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tiporequerimiento'),
        ),
        migrations.CreateModel(
            name='LogEstadoProyecto',
            fields=[
                ('idLogEstadoProyecto', models.AutoField(primary_key=True, serialize=False)),
                ('usuarioRegistro', models.CharField(max_length=20)),
                ('fechaRegistro', models.DateField()),
                ('idEstadoProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.estadoproyecto')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
        ),
    ]
