# Generated by Django 3.2.4 on 2024-10-27 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0003_auto_20241025_0034'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRequerimiento',
            fields=[
                ('idEstadoRequerimiento', models.AutoField(primary_key=True, serialize=False)),
                ('estadoRequerimiento', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('idRequerimiento', models.AutoField(primary_key=True, serialize=False)),
                ('requerimiento', models.CharField(max_length=150)),
                ('orden', models.IntegerField()),
                ('fechaEstimadoEntrega', models.DateField()),
                ('fechaInicioPropuesto', models.DateField()),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('idEstadoRequerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimiento.estadorequerimiento')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
                ('idUsuariEncargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimiento_encargado', to=settings.AUTH_USER_MODEL)),
                ('idUsuarioRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimiento_registro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
