# Generated by Django 3.2.4 on 2024-11-02 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prueba', '0006_auto_20241101_2336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('idBug', models.AutoField(primary_key=True, serialize=False)),
                ('bug', models.CharField(max_length=60)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaResolucion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('idClasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('clasificacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoBug',
            fields=[
                ('idEstadoBug', models.AutoField(primary_key=True, serialize=False)),
                ('estadoBug', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='LogEstadoBug',
            fields=[
                ('idLogEstadoBug', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('idBug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logsBug', to='bug.bug')),
                ('idEstadoBug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logsEstado', to='bug.estadobug')),
                ('idUsuarioRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_usaurioRegsitro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='idClasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='bug.clasificacion'),
        ),
        migrations.AddField(
            model_name='bug',
            name='idEstadoBug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='bug.estadobug'),
        ),
        migrations.AddField(
            model_name='bug',
            name='idPrueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.prueba'),
        ),
        migrations.AddField(
            model_name='bug',
            name='idUsuarioEncargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_encargado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bug',
            name='idUsuarioRegistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_registro', to=settings.AUTH_USER_MODEL),
        ),
    ]
